// Default rule configurations for each game mode
const GAME_MODES = {
  hideAndSeek: {
    id: 'hideAndSeek',
    name: 'Hide & Seek',
    icon: '👁️',
    description: 'Classic hide and seek. Seekers hunt hiders until all are caught.',
    teamNames: { seekers: 'Seekers', hiders: 'Hiders' },
    defaultSeekerCount: 2,
    gameDuration: 15, // minutes
    countdownTime: 60, // seconds before seekers can move
    features: {
      shrinkingZone: { enabled: true, intervalMinutes: 5, warningSeconds: 30 },
      locationPings: { enabled: true, intervalMinutes: 5, durationSeconds: 10 },
      audioTrap: { enabled: true, intervalMinutes: 3, randomVarianceMinutes: 2 },
      lotteryDraft: { enabled: true },
      traitorMechanic: { enabled: false, activateAtMinute: 8 },
      supplyCaches: { enabled: false, cacheCount: 3, jammerDurationSeconds: 60 },
      jailbreakTerminals: { enabled: true, terminalCount: 2, holdSeconds: 15 },
      decoyDeployments: { enabled: false, decoyCount: 2 },
      vipEscort: { enabled: false, vipPoints: 500 },
      proximityAlarms: { enabled: false, alarmCount: 3 },
      assassinClass: { enabled: false },
      blackoutProtocol: { enabled: false, durationSeconds: 60 },
      bountyContracts: { enabled: false, bountyDurationMinutes: 3, bountyPoints: 200 },
      paranoiaTimer: { enabled: true, stillnessMinutes: 4, requiredMovementFeet: 30 },
      indoorMode: { enabled: true },
      outdoorMode: { enabled: false },
    },
    scoring: {
      hiderSurvivalBonus: 10, // per minute survived
      seekerCatchBonus: 50,
      jailbreakBonus: 75,
    },
  },

  copsAndRobbers: {
    id: 'copsAndRobbers',
    name: 'Cops & Robbers',
    icon: '🚔',
    description: 'Robbers try to reach the safe zone. Cops tag and jail them.',
    teamNames: { seekers: 'Cops', hiders: 'Robbers' },
    defaultSeekerCount: 3,
    gameDuration: 20,
    countdownTime: 30,
    features: {
      shrinkingZone: { enabled: true, intervalMinutes: 7, warningSeconds: 30 },
      locationPings: { enabled: true, intervalMinutes: 4, durationSeconds: 10 },
      audioTrap: { enabled: false, intervalMinutes: 4, randomVarianceMinutes: 1 },
      lotteryDraft: { enabled: true },
      traitorMechanic: { enabled: false, activateAtMinute: 10 },
      supplyCaches: { enabled: true, cacheCount: 4, jammerDurationSeconds: 45 },
      jailbreakTerminals: { enabled: true, terminalCount: 3, holdSeconds: 15 },
      decoyDeployments: { enabled: true, decoyCount: 2 },
      vipEscort: { enabled: false, vipPoints: 400 },
      proximityAlarms: { enabled: true, alarmCount: 4 },
      assassinClass: { enabled: false },
      blackoutProtocol: { enabled: false, durationSeconds: 60 },
      bountyContracts: { enabled: true, bountyDurationMinutes: 3, bountyPoints: 300 },
      paranoiaTimer: { enabled: true, stillnessMinutes: 3, requiredMovementFeet: 25 },
      indoorMode: { enabled: true },
      outdoorMode: { enabled: false },
    },
    scoring: {
      hiderSurvivalBonus: 8,
      seekerCatchBonus: 60,
      jailbreakBonus: 100,
    },
  },

  infection: {
    id: 'infection',
    name: 'Infection',
    icon: '🦠',
    description: 'One infected player must spread the infection to all others.',
    teamNames: { seekers: 'Infected', hiders: 'Survivors' },
    defaultSeekerCount: 1,
    gameDuration: 15,
    countdownTime: 20,
    features: {
      shrinkingZone: { enabled: true, intervalMinutes: 4, warningSeconds: 30 },
      locationPings: { enabled: false, intervalMinutes: 5, durationSeconds: 10 },
      audioTrap: { enabled: true, intervalMinutes: 2, randomVarianceMinutes: 2 },
      lotteryDraft: { enabled: true },
      traitorMechanic: { enabled: false, activateAtMinute: 7 },
      supplyCaches: { enabled: true, cacheCount: 3, jammerDurationSeconds: 30 },
      jailbreakTerminals: { enabled: false, terminalCount: 2, holdSeconds: 15 },
      decoyDeployments: { enabled: true, decoyCount: 1 },
      vipEscort: { enabled: false, vipPoints: 300 },
      proximityAlarms: { enabled: true, alarmCount: 3 },
      assassinClass: { enabled: false },
      blackoutProtocol: { enabled: true, durationSeconds: 60 },
      bountyContracts: { enabled: false, bountyDurationMinutes: 3, bountyPoints: 150 },
      paranoiaTimer: { enabled: true, stillnessMinutes: 3, requiredMovementFeet: 20 },
      indoorMode: { enabled: true },
      outdoorMode: { enabled: false },
    },
    scoring: {
      hiderSurvivalBonus: 15,
      seekerCatchBonus: 40,
      jailbreakBonus: 0,
    },
  },

  battleRoyale: {
    id: 'battleRoyale',
    name: 'Battle Royale',
    icon: '💀',
    description: 'All mechanics active. Maximum chaos. Last hider standing wins.',
    teamNames: { seekers: 'Hunters', hiders: 'Survivors' },
    defaultSeekerCount: 4,
    gameDuration: 25,
    countdownTime: 90,
    features: {
      shrinkingZone: { enabled: true, intervalMinutes: 4, warningSeconds: 30 },
      locationPings: { enabled: true, intervalMinutes: 5, durationSeconds: 10 },
      audioTrap: { enabled: true, intervalMinutes: 3, randomVarianceMinutes: 2 },
      lotteryDraft: { enabled: true },
      traitorMechanic: { enabled: true, activateAtMinute: 12 },
      supplyCaches: { enabled: true, cacheCount: 5, jammerDurationSeconds: 60 },
      jailbreakTerminals: { enabled: true, terminalCount: 3, holdSeconds: 15 },
      decoyDeployments: { enabled: true, decoyCount: 2 },
      vipEscort: { enabled: true, vipPoints: 500 },
      proximityAlarms: { enabled: true, alarmCount: 4 },
      assassinClass: { enabled: true },
      blackoutProtocol: { enabled: true, durationSeconds: 60 },
      bountyContracts: { enabled: true, bountyDurationMinutes: 3, bountyPoints: 250 },
      paranoiaTimer: { enabled: true, stillnessMinutes: 4, requiredMovementFeet: 30 },
      indoorMode: { enabled: true },
      outdoorMode: { enabled: false },
    },
    scoring: {
      hiderSurvivalBonus: 12,
      seekerCatchBonus: 75,
      jailbreakBonus: 100,
    },
  },

  custom: {
    id: 'custom',
    name: 'Custom',
    icon: '⚙️',
    description: 'Build your own game. Toggle any feature and set your own rules.',
    teamNames: { seekers: 'Team A', hiders: 'Team B' },
    defaultSeekerCount: 2,
    gameDuration: 20,
    countdownTime: 60,
    features: {
      shrinkingZone: { enabled: false, intervalMinutes: 5, warningSeconds: 30 },
      locationPings: { enabled: false, intervalMinutes: 5, durationSeconds: 10 },
      audioTrap: { enabled: false, intervalMinutes: 3, randomVarianceMinutes: 2 },
      lotteryDraft: { enabled: true },
      traitorMechanic: { enabled: false, activateAtMinute: 8 },
      supplyCaches: { enabled: false, cacheCount: 3, jammerDurationSeconds: 60 },
      jailbreakTerminals: { enabled: false, terminalCount: 2, holdSeconds: 15 },
      decoyDeployments: { enabled: false, decoyCount: 2 },
      vipEscort: { enabled: false, vipPoints: 400 },
      proximityAlarms: { enabled: false, alarmCount: 3 },
      assassinClass: { enabled: false },
      blackoutProtocol: { enabled: false, durationSeconds: 60 },
      bountyContracts: { enabled: false, bountyDurationMinutes: 3, bountyPoints: 200 },
      paranoiaTimer: { enabled: false, stillnessMinutes: 4, requiredMovementFeet: 30 },
      indoorMode: { enabled: true },
      outdoorMode: { enabled: false },
    },
    scoring: {
      hiderSurvivalBonus: 10,
      seekerCatchBonus: 50,
      jailbreakBonus: 75,
    },
  },
};

module.exports = { GAME_MODES };
